# Generated by Django 5.1.5 on 2025-05-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pynkmail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useremailsettings",
            name="MailAllowance",
            field=models.IntegerField(default=1000),
        ),
    ]
